웹 프로젝트/flea_market/final_project/final_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flea_market/', include('flea_market.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

웹 프로젝트/flea_market/final_project/flea_market/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'flea_market'
urlpatterns = [
	path('', views.homepage, name = 'homepage'),
	path('admin/', views.admin, name = 'admin'),
	path('login/', views.login, name = 'login'),
	path('signup/', views.signup, name = 'signup'),
	path('purchase_list/', views.purchase_list, name = 'purchase_list'),
	path('shopping_list/', views.shopping_list, name = 'shopping_list'),
	path('wish_list/', views.wish_list, name = 'wish_list'),
	path('auction/', views.auction, name = 'auction'),
	path('my_item/', views.my_item, name = 'my_item'),
	path('my_item/<int:item_id>/', views.modify_item, name = 'modify_item'),
	path('registration/', views.registration, name = 'registration'),
	path('<int:item_id>/', views.item, name = 'item'),
	path('<str:search>/', views.search_item, name = 'search_item'),
	path('<int:item_id>/report/', views.report, name = 'report'),
	path('admin/<int:report_id>/', views.show_report, name = 'show_report'),
	path('admin/user/', views.show_user, name = 'show_user'),
	path('admin/user/<str:user_id>/', views.modify_user, name = 'modify_user'),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

웹 프로젝트/flea_market/final_project/flea_market/models.py
from django.db import models
import datetime

class MyUser(models.Model):	
	first_name = models.CharField(max_length= 15)
	last_name = models.CharField(max_length= 15)
	user_id = models.CharField(max_length= 15, primary_key=True)
	password = models.CharField(max_length = 15)
	email = models.CharField(max_length = 30)
	phone_number = models.CharField(max_length=15)
	address = models.CharField(max_length=100)
	ban_counter = models.IntegerField(default=0)

class Item(models.Model):
	myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
	seller_name = models.CharField(max_length = 50)
	item_name = models.CharField(max_length = 50)
	price = models.IntegerField()
	immediate = models.IntegerField(default = 0)
	picture = models.ImageField(upload_to = "%Y/%m/%d")
	explain = models.CharField(max_length = 500, default = "None")
	auction = models.IntegerField(default = 0)
	trading_place = models.CharField(max_length = 500, default = "None")
	likes = models.IntegerField(default = 0)
	upload_item = models.DateTimeField()
	end_time = models.DateTimeField()
	sold_out = models.IntegerField(default = 0)

class Review(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	user_id = models.CharField(max_length = 15)
	review = models.CharField(max_length = 400)

class ShoppingList(models.Model):
	myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)

class Like(models.Model):
	myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)

class Report(models.Model):
	myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
	title = models.CharField(max_length = 50)
	reported_user_id = models.CharField(max_length = 15)
	reported_item = models.CharField(max_length = 15)
	report_content = models.TextField()
	picture = models.ImageField(upload_to = "report")

class MyAuction(models.Model):
	myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	bidding = models.IntegerField()

class PurchaseList(models.Model):
	myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)

# Create your models here.

웹 프로젝트/flea_market/final_project/flea_market/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.models import User
import os
from django.conf import settings
from datetime import datetime
from datetime import tzinfo,timedelta,datetime
from pytz import timezone

from .models import MyUser, Item, ShoppingList, Report, Review, MyAuction, PurchaseList, Like

def check_sold():

	items = Item.objects.all()
	auc = MyAuction.objects.values('id', 'item_id', 'myuser_id')
	for row in items:
		real_time = datetime.now();
		real_time = real_time.astimezone(timezone('Asia/Seoul'))
		if row.end_time < real_time:
			if row.auction:
				Item.objects.filter(id = row.id).update(sold_out = 1)
				for auct in auc:
					if auct['item_id'] == row.id:
						myauc = MyAuction.objects.get(pk = auct['id'])
						new_purchase = PurchaseList(myuser_id = auct['myuser_id'], item_id = auct['item_id'])
						new_purchase.save()
						myauc.delete()
	return

def homepage(request):
	check_sold()
	items = Item.objects.all().order_by('-id')
	if request.method == "POST":
		search = request.POST.get('search', False)
		search_product = request.POST.get('search_product', False)
		search_seller = request.POST.get('search_seller', False)
		price = request.POST.get('price', 0)
		auction = request.POST.get('auction', 0)
		if search_product or search_seller or price or auction:
			total_search = ""
			total_search += search_product + "@" + search_seller + "@" + str(price) + "@" + str(auction) + "@"
			return HttpResponseRedirect(reverse('flea_market:search_item', args=(total_search,)))
		elif search:
			return HttpResponseRedirect(reverse('flea_market:search_item', args=(search,)))
	
	user_id = request.user.username
	if user_id != "":
		user = MyUser.objects.get(pk = user_id)
		return render(request, 'homepage.html', {'name': user, 'items': items})
	return render(request, 'homepage.html', {'items': items})

def admin(request):
	check_sold()
	report = Report.objects.all().order_by('-id')
	return render(request, 'admin.html', {'reports': report})

def show_report(request, report_id):
	check_sold()
	report = Report.objects.get(pk = report_id)
	report_user = MyUser.objects.get(pk = report.myuser_id)
	reported_user = MyUser.objects.get(pk = report.reported_user_id)
	if request.method == "POST":
		report.delete()
		return HttpResponseRedirect(reverse('flea_market:admin'))
	return render(request, 'admin_report.html', {'report':report, 'report_user': report_user, 'reported_user': reported_user})

def show_user(request):
	check_sold()
	user = MyUser.objects.all()
	return render(request, 'admin_user.html', {'users': user})

def modify_user(request, user_id):
	check_sold()
	user = MyUser.objects.get(pk = user_id)
	if request.method == "POST":
		if request.POST.get('mod_btn', False):
			MyUser.objects.filter(user_id = user_id).update(user_id = request.POST.get('user_id', False), first_name = request.POST.get('first_name', False), last_name = request.POST.get('last_name',False), password = request.POST.get('password', False), email = request.POST.get('email', False), phone_number = request.POST.get('phone_number', False), address = request.POST.get('address', False), ban_counter = request.POST.get('ban_counter', False))
			return HttpResponseRedirect(reverse('flea_market:show_user'))
		if request.POST.get('del_btn', False):
			user.delete()
			u = User.objects.get(username = user_id)
			u.delete()
			return HttpResponseRedirect(reverse('flea_market:show_user'))

	return render(request, 'admin_modify.html', {'user': user})

def search_item(request, search):
	check_sold()
	user_id = request.user.username
	user = MyUser.objects.filter(user_id = user_id)
	product = []
	seller = []
	if "@" in search:
		search_ = search.split("@")
		search_product = search_[0]
		search_seller = search_[1]
		price = int(search_[2])
		if price == 91 or price == 0:
			price = 1000000000
		auction = int(search_[3])
		items = Item.objects.all().order_by('-id')
		for row in items:
			if int(row.price) <= price and row.sold_out == 0:
				if search_product != "" and search_seller != "":
					if search_product in row.item_name and search_seller in row.seller_name:
						if auction == row.auction:
							product.append(row)
				elif search_product != "" and search_product in row.item_name:
					if auction == row.auction:
						product.append(row)
				elif search_seller != "" and search_seller in row.seller_name:
					if auction == row.auction:
						seller.append(row)
				elif search_product == "" and search_seller == "":
					if auction == row.auction:
						seller.append(row)

	else:
		items = Item.objects.all().order_by('-id')
		if search == "None":
			product = items
		else:
			for row in items:
				if row.sold_out == 0:
					if search in row.item_name:
						product.append(row)
					elif search in row.seller_name:
						seller.append(row)
	if request.method == "POST":
		search = request.POST.get('search', False)
		search_product = request.POST.get('search_product', False)
		search_seller = request.POST.get('search_seller', False)
		price = request.POST.get('price', 0)
		auction = request.POST.get('auction', 0)
		if search_product or search_seller or price or auction:
			total_search = ""
			total_search += search_product + "@" + search_seller + "@" + str(price) + "@" + str(auction) + "@"
			return HttpResponseRedirect(reverse('flea_market:search_item', args=(total_search,)))
		elif search:
			return HttpResponseRedirect(reverse('flea_market:search_item', args=(search,)))
	
	return render(request, 'search.html', {'name': user, 'product': product, 'seller': seller})

def login(request):
	check_sold()
	auth.logout(request)
	if request.method == "POST":
		input_id = request.POST.get('inputID', False)
		input_pw = request.POST.get('inputPassword', False)
		if len(input_id) == 0 or len(input_pw) == 0:
			return render(request, 'login.html', {'msg': "Check your ID or Password"})
		users = MyUser.objects.values('user_id', 'password', 'ban_counter')
		for row in users:
			if row['user_id'] == input_id and row['password'] == input_pw:
				if row['ban_counter'] >= 5:
					return render(request, 'login.html', {'msg': "Your account is suspended"})
				user = auth.authenticate(request, username=input_id, password = input_pw)
				auth.login(request,user)
				if input_id == "admin":
					return HttpResponseRedirect(reverse('flea_market:admin'))
				return HttpResponseRedirect(reverse('flea_market:homepage'))
		return render(request, 'login.html', {'msg': "Check your ID or Password"})
	return render(request, 'login.html')

signup_id = False
def signup(request):
	check_sold()
	global signup_id
	if request.method == "POST":
		if request.POST.get('check_btn', False):
			signup_id = request.POST.get('username', False)
			if len(signup_id) == 0:
				signup_id = False
				return render(request, 'signup.html', {'msg': "Please input ID"})

			user = MyUser.objects.values('user_id')
			for row in user:
				if row['user_id'] == signup_id:
					signup_id = False
					return render(request, 'signup.html', {'msg': "This ID already exists"})
			return render(request, 'signup.html', {'signup_id':signup_id, 'msg': "You can use this ID"})
		else:
			if signup_id:
				if request.POST.get('password',False) == request.POST.get('confirm', False):
					phone = request.POST.get('phone', False)
					if len(phone) != 13 or phone[3] != "-" or phone[8] != "-":
						return render(request, 'signup.html', {'msg': "Please enter correct phone number"})
					new_user = MyUser(user_id = signup_id, first_name = request.POST.get('firstName', False), last_name = request.POST.get('lastName',False), password = request.POST.get('password', False), email = request.POST.get('email', False), phone_number = request.POST.get('phone', False), address = request.POST.get('address', False), ban_counter = 0)
					new_user.save()
					User.objects.create_user(username = new_user.user_id, password = new_user.password)
					signup_id = False
					return HttpResponseRedirect(reverse('flea_market:login'))
				return render(request, 'signup.html', {'msg': "Please confirm your password"})
			else:
				return render(request, 'signup.html', {'signup_id':signup_id, 'msg': "Please check your ID first"})
	return render(request, 'signup.html')


def purchase_list(request):
	check_sold()
	user_id = request.user.username
	user = MyUser.objects.get(pk = user_id)
	purchase_list = PurchaseList.objects.filter(myuser_id = user.user_id)

	if request.method == "POST":
		if request.POST.get('del_all_btn', False):
			purchase_list.delete()
		else:
			search = request.POST.get('search', False)
			search_product = request.POST.get('search_product', False)
			search_seller = request.POST.get('search_seller', False)
			price = request.POST.get('price', 0)
			auction = request.POST.get('auction', 0)
			if search_product or search_seller or price or auction:
				total_search = ""
				total_search += search_product + "@" + search_seller + "@" + str(price) + "@" + str(auction) + "@"
				return HttpResponseRedirect(reverse('flea_market:search_item', args=(total_search,)))
			elif search:
				return HttpResponseRedirect(reverse('flea_market:search_item', args=(search,)))
	my_list = []
	sum_price = 0
	for row in purchase_list:
		my_list.append(Item.objects.get(pk = row.item_id))
		sum_price += Item.objects.get(pk = row.item_id).price
	return render(request, 'purchase_list.html', {'name': user, 'list': my_list, 'sum': sum_price})

def wish_list(request):
	check_sold()
	user_id = request.user.username
	user = MyUser.objects.get(pk = user_id)
	if request.method == "POST":
		if request.POST.get('del_btn', False):
			delete_item = Like.objects.filter(item_id = request.POST.get('del_btn', False))
			like_item = Item.objects.get(pk = request.POST.get('del_btn', False))
			Item.objects.filter(id = like_item.id).update(likes = like_item.likes - 1)
			delete_item.delete()

웹 프로젝트/flea_market/final_project/flea_market/templates/admin_nav.html
{% extends 'base.html' %}
{% block content %}
<header>

  <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <a class="navbar-brand" href="/flea_market/admin/"><img src="/static/homepage_images/logo.jpg" width="250" height="60" alt="Market Logo"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample09">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/flea_market/login" style="color: blue !important;">Logout <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/flea_market/admin/user"!important;">User <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      
    </div>
  </nav>
</header>
{% block admin_nav %}
{% endblock %}
{% endblock %}

웹 프로젝트/flea_market/final_project/flea_market/templates/admin_report.html
{% extends 'admin.html' %}
{% block admin_nav %}

<main role="main" class="container">

  <div class="my-2 p-2 bg-white rounded shadow-sm">
  <form method="POST">
  {% csrf_token %}
    <div class="row mb-3">
      <div class="col-4">
      </div>
      <div class="col-4">
      <p style="text-align: center;">{{report.title}}</p>
      </div>
      
    </div>
    <div class="row mb-3">
      <div class="col-6">
      <h6 style="text-align: center;">Report User ID: {{report_user.user_id}}<a href="/flea_market/admin/user/{{report_user.user_id}}"> modify</a></h6>
      </div>
      <div class="col-6">
        <h6 style="text-align: center;">Reported User ID: {{reported_user.user_id}}<a href="/flea_market/admin/user/{{reported_user.user_id}}"> modify</a></h6>
      </h6>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-4">
        
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-4">
        <h6 style="">content</h6>
      </div>
    </div>      
        <p>{{report.report_content}}</p>
    </div>
    <div class="row mb-3">
      <div class="col-4">
        
      </div>
      <div class="col-4">
        
      </div>
      <div class="col-4">
      <button class="btn btn-primary btn-lg btn-block" type="submit" name="del_btn" value="1">Delete</button>
      </div>
    </div>
  </form>
  </div>
</main>
{% endblock %}

웹 프로젝트/flea_market/final_project/flea_market/templates/admin_user.html
{% extends 'admin.html' %}
{% block admin_nav %}

<main role="main" class="container">

  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="row mb-3">
      <div class="col-4">
        <h6 class="border-bottom border-gray pb-2 mb-0">User</h6>
      </div>
      <div class="col-4">
      <h6 class="border-bottom border-gray pb-2 mb-0">Type</h6>
      </div>
      <div class="col-4">
      <h6 class="border-bottom border-gray pb-2 mb-0">Ban counter</h6>
      </div>
    </div>
    {% for user in users %}
    <div class="row mb-3">
      <div class="col-4">
        {% if user.user_id == "admin" %}
          admin
        {% else %}
        <a href="/flea_market/admin/user/{{user.user_id}}" class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <h6>@ {{user.user_id}}</h6>
        {% endif %}
        </a>
      </div>
      <div class="col-4">
        {% if user.user_id == "admin" %}
        admin
        {% else %}
        User
        {% endif %}
      </div>
      <div class="col-4">
        {% if user.user_id == "admin" %}
        admin
        {% else %}
        {{user.ban_counter}}
        {% endif %}
      </div>
    </div>
    {% endfor %}
    </div>
</main>
{% endblock %}

웹 프로젝트/flea_market/final_project/flea_market/templates/auction.html
{% extends 'nav.html' %}
{% block nav %}
<main role="main">

  <div class="album py-5 bg-light">
    <div class="container">
      <center><h2>My Auction</h2></center>
      <form method="POST">
      {% csrf_token %}
      <div class="row">
      {% for item in list %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm" style="height: auto !important;">
            {% if item.picture != "False"%}
            <img src="{{item.picture.url}}" style="height: 225px !important" x="50%" y="50%" >
            {% else %}
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/>
            <text x="50%" y="50%" fill="#eceeef" dy=".3em">No Picture</text>
            </svg>
            {% endif %}
            <div class="card-body">
              <a href="/flea_market/{{item.id}}"><center><h6>{{item.item_name}}</h6></center>
              <br>
              {% if item.auction ==  1%}
              <i class="fas fa-gavel"></i>
              {% endif %}
              <h8>
              {% if item.sold_out == 0 %}
              {{item.price}} $
              <div style="float: right">
              Likes: {{item.likes}}
              </div>
              {% else %}
              Sold out
              {% endif %}
              </h8>
              </a>
              
            </div>
          </div>
        </div>
        {% endfor %}
        
        {% if sum == 0 %}
        <div class="container">
        <br>
        <center><p>There are no items</p></center>
        </div>
        {% endif %}
      </div>
        </form>
    </div>
  </div>

</main>

{% endblock %}

웹 프로젝트/flea_market/final_project/flea_market/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Flea Market</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sticky-footer/">

    <!-- Bootstrap core CSS -->
<link href="/static/css/assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="/static/css/navbar.css" rel="stylesheet">
    <link href="/static/css/album.css" rel="stylesheet">
    <link href="/static/css/carousel.css" rel="stylesheet">
    <link href="/static/css/assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/form-validation.css" rel="stylesheet">
    
    <script src="https://kit.fontawesome.com/ff36ada265.js" crossorigin="anonymous"></script>
  </head>
<body style="margin: 0 !important; height: 100% !important;">
{% block content %}
{% endblock %}

<footer class="footer mt-auto py-3" style="height: 30px !important; bottom: 0; position: relative; margin-top: -50px;">
  <div style="width: auto; padding: 0 15px; height: 50px !important;">
    <span class="text-muted" style="height: 30px; bottom: 0">(C) Sung Kyun Kwan University Software 2016313746 Yu Jae Hun All right reserved</span>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/static/css/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/static/css/assets/dist/js/bootstrap.bundle.min.js"></script>
<script src="/static/css/offcanvas.js"></script>
</script>
      <script>window.jQuery || document.write('<script src="/static/css/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/static/css/assets/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/static/css/form-validation.js"></script>

</body>
</html>

웹 프로젝트/flea_market/final_project/flea_market/templates/signup.html
{% extends 'base.html' %}
{% block content %}

  <body class="bg-light">
{% if msg %}
    <script type="text/javascript">
      alert("{{msg}}")
      window.history.back();
    </script>
  {% endif %}
 <div class="container" style="">
  <div class="py-5">
    <a href="/flea_market"><img class="d-block mx-auto mb-4" src="/static/homepage_images/logo.jpg" alt="" width="250" height="72"></a>
  </div>
      <h4 class="mb-3">SIGN UP</h4>
      <form action="{% url 'flea_market:signup' %}" method="POST" novalidate>
      {% csrf_token %}
      <div class="row">

        <div class="col-md-6 mb-3">
          <label for="Username">ID</label>
          <div class="input-group">
            <input type="text" class="form-control" name="username" placeholder="ID" value="{{signup_id}}">
            <button type="submit" name="check_btn" style="border: 0px" value="1">CHECK</button>
            <div class="valid-feedback" style="width: 100%;">
              Your ID is required.
            </div>            
          </div>
          </div>
          </div>
      </form>
      <form action="{% url 'flea_market:signup' %}" method="POST" class="needs-validation" novalidate>
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="password">Password</label>
          <input type="password" class="form-control" name="password" placeholder="" required>
          <div class="invalid-feedback">
            Please enter your password.
          </div>
        </div> 

        <div class="col-md-6 mb-3">
          <label for="confirm">Confirm Password</label>
          <input type="password" class="form-control" name="confirm" placeholder="" required>
          <div class="invalid-feedback">
            Please confirm your password.
          </div>
        </div> 
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" name="firstName" placeholder="" value="" required>

            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" name="lastName" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>
        <div class="mb-3">
          <label for="email">Email <span class="text-muted">(Optional)</span></label>
          <input type="email" class="form-control" name="email" placeholder="you@example.com">
          <div class="invalid-feedback">
            Please enter a valid email address
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" name="address" placeholder="1234 Main St" required>
          <div class="invalid-feedback">
            Please enter your address.
          </div>
        </div>

         <div class="mb-3">
          <label for="Phone">Phone Number</label>
          <input type="text" class="form-control" name="phone" placeholder="010-1234-5678" required>
          <div class="invalid-feedback">
            Please enter your phone number.
          </div>
        </div> 
          
        
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">SIGN UP</button>
        </div> 
      </form>
  </div>
<br><br><br>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/static/css/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/static/css/assets/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/static/css/form-validation.js"></script></body>

{% endblock %}